### ISSUE TITLE
train_15dB is missing

### ISSUE THREAD

**Issue by Senzt** [sivasuryas/speech_corpora#1]
Dear Sivu1, 

Could you re-upload the file, train_15dB?

Best Regards,

**Comment by chmodsss** [comment]
I just saw the issue. Well, better late than never.

**Comment by Sarkhell** [comment]
train_15dB is missing #1
It is still missing from this link: https://ecs.utdallas.edu/loizou/speech/noizeus/
We appreciate it.. if you reload it again

**Comment by chmodsss** [comment]
Hi @Sarkhell I am not the maintainer of the Noizeus dataset in the UT Dallas webpage. This repository was created so that it would be easy to just download the entire dataset in one go. The train_15dB is present in this repository and that's all I can manage.
